### ISSUE TITLE
hi. we get this error

### ISSUE THREAD

**Issue by azizsan** [andDevW/AEQ#2]
hi. we get this error

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.anddevw.aeq, PID: 4614
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.anddevw.aeq/com.anddevw.aeq.MainActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME,android.intent.category.LAUNCHER] flg=0x4000000 pkg=com.android.launcher }
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                   Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME,android.intent.category.LAUNCHER] flg=0x4000000 pkg=com.android.launcher }
                      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
                      at android.app.Activity.startActivityForResult(Activity.java:4225)
                      at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                      at android.app.Activity.startActivityForResult(Activity.java:4183)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
                      at android.app.Activity.startActivity(Activity.java:4522)
                      at android.app.Activity.startActivity(Activity.java:4490)
                      at com.anddevw.aeq.MainActivity.quickReturn(MainActivity.java:50)
                      at com.anddevw.aeq.MainActivity.openEqualizer(MainActivity.java:40)
                      at com.anddevw.aeq.MainActivity.onCreate(MainActivity.java:27)
                      at android.app.Activity.performCreate(Activity.java:6679)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6119) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
Application terminated.
`

**Comment by andDevW** [comment]
Are you using the app on a Nexus or Pixel device?

**Comment by AKprisonER** [comment]
Yeah..   i did so, but the recent commit I made was stuck with some gradle
errors.

 Will solve it by Tmw.....Hope u make new dependencies for my gitlab repo

**Comment by azizsan** [comment]
thanks the problem is solved :)
